/*
 *Each new term in the Fibonacci sequence is generated by adding the previous two
 *terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *By considering the terms in the Fibonacci sequence whose values do not exceed
 *four million, find the sum of the even-valued terms.
 */

package main

import "fmt"

func even_fib_sum(max int) int {
	a, b, sum := 1, 2, 0
	for a < max && b < max {
		if a%2 == 0 {
			sum += a
		}
		if b%2 == 0 {
			sum += b
		}
		a = a + b
		b = a + b
	}
	return sum
}

func main() {
	fmt.Println(even_fib_sum(3))
	fmt.Println(even_fib_sum(14))
	fmt.Println(even_fib_sum(58))
	fmt.Println(even_fib_sum(4000000))
}
